spring:
  application:
    name: uphi-backend

  data:
    mongodb:
      uri: ${MONGODB_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.0-flash
